name: run-cypress-tests
on: 
  workflow_dispatch:
    inputs:
      browser:
        description: Browser     
        required: true
        default: chrome 
        type: choice
        options:
        - chrome
        - firefox

jobs:
  cypress-run-docker:
    if: github.actor == 'hrmeetsingh'
    runs-on: ubuntu-latest
    name: E2E on ${{ github.event.inputs.browser }} running on a docker container
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker test
        uses: ./.github/workflows/e2e_action
        with:
          container-args: ${{ github.event.inputs.browser }}
