name: run-cypress-tests
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: string

jobs:
  cypress-run-docker:
    runs-on: ubuntu-latest
    name: E2E on Chrome running on a docker container
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker test
        uses: ./.github/workflows
        with:
          container-args: Test
