name: run-cypress-tests
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      env:
        LEVEL: ${{ github.event.inputs.logLevel }}
        TAGS: ${{ github.event.inputs.tags }}
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
