name: run-cypress-tests
on: 
  workflow_dispatch:
    inputs:
      browser:
        description: Browser     
        required: true
        default: chrome 
        type: choice
        options:
        - chrome
        - firefox

jobs:
  cypress-run:
    if: github.actor == 'hrmeetsingh'
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: ${{ github.event.inputs.browser }}
